server:
  port: 8086
spring:
  redis:
    host: 192.168.147.130
    port: 6379
    password: root

dubbo:
  application:
    name: server-consumer
  registry:
    address: zookeeper://192.168.147.130:2181
    check: false
